#!/bin/sh

# Should we use -Xshare:on? @msailes did originally...
# -Xlog:cds is important for solving the CDS problem.
/opt/jre21-slim/bin/java --add-opens java.base/java.util=ALL-UNNAMED -XX:+TieredCompilation -XX:TieredStopAtLevel=1 -Xshare:auto -cp "/opt/aws-lambda-java-runtime-interface-client-2.4.1.jar:/opt/aws-lambda-java-core-1.2.3.jar:/opt/aws-lambda-java-serialization-1.1.2.jar:$LAMBDA_TASK_ROOT:$LAMBDA_TASK_ROOT/*:$LAMBDA_TASK_ROOT/lib/*" com.amazonaws.services.lambda.runtime.api.client.AWSLambda "$_HANDLER"
